### ISSUE TITLE
Heroku Config Variables Not Detected by Laravel

### ISSUE THREAD

**Issue by iamdejan** [iamdejan/quickshoot-party-data-server#5]
![Screen Shot 2019-07-04 at 16 17 58](https://user-images.githubusercontent.com/15686093/60656045-faa6a480-9e78-11e9-99cb-1898266479e2.png)

**Comment by nieltg** [comment]
@iamdejan Have you followed this guide?

https://devcenter.heroku.com/articles/config-vars

**Comment by iamdejan** [comment]
> https://devcenter.heroku.com/articles/config-vars

Yes, and for me, it's not very helpful. 😢

**Comment by iamdejan** [comment]
Solution:
Use `heroku run bash -a quickshoot-party-data-server`
